title: Harpreet's learning blog
description: Space to share experience and thoughts
author: "Harpreet Singh"
url: "https://blog.geekfive.co.uk"

remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Social links (shown in footer)
github_username: har-singh

# Blog settings
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  skin: auto

# Navigation menu (order matters)
header_pages:
  - about.md
  - archive.md

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - vendor
